const nonVegetarianIngredients = [
  'Anchovies',
  'Anchovy fillet',
  'Bacon',
  'Chicken Breasts',
  'Chicken Stock',
  'Chicken',
  'Doner Meat',
  'Lamb loin chops',
  'Lamb mince',
  'Lean Minced Beef',
  'Oyster Sauce',
  'Prawns',
  'Raw King Prawns',
  'Salmon',
  'Shredded Monterey Jack Cheese',
  'Tinned Tuna',
  'Tuna',
];
const nonVeganIngredients = [
  [...nonVegetarianIngredients],
  'Butter, softened',
  'Butter',
  'Chilled Butter',
  'Cream',
  'Creme Fraiche',
  'Egg White',
  'Egg Yolk',
  'Egg',
  'Eggs',
  'Free-range Egg, Beaten',
  'Free-range Eggs, Beaten',
  'Half-and-half',
  'Heavy cream',
  'Ice-Cream',
  'Milk',
  'Whipped Cream',
  'Whipping Cream',
  'Yoghurt',
];

const alcoholIngredients = [
  '151 proof rum',
  'Absinthe',
  'Absolut citron',
  'Absolut Kurant',
  'Absolut Vodka',
  'Aejo rum',
  'Ale',
  'Amaretto',
  'Apricot Brandy',
  'Aquavit',
  'A¤ejo rum',
  'Bacardi Limon',
  'Bacardi',
  "Bailey's irish cream",
  'Baileys irish cream',
  'Banana liqueur',
  'Beer',
  'Benedictine',
  'Blackberry Brandy',
  'Blackberry schnapps',
  'Blended Whiskey',
  'Blue Curacao',
  'Blueberry schnapps',
  'Bourbon',
  'Brandy',
  'Butterscotch schnapps',
  'Cachaca',
  'Calvados',
  'Campari',
  'Chambord raspberry liqueur',
  'Champagne',
  'Cherry Brandy',
  'Cognac',
  'Cointreau',
  'Coconut liqueur',
  'Coconut rum',
  'Coffee brandy',
  'Coffee liqueur',
  'Crown Royal',
  'Dark Creme de Cacao',
  'Dark Rum',
  'Dry Vermouth',
  'Dubonnet Rouge',
  'Everclear',
  'Frangelico',
  'Galliano',
  'Gin',
  'Goldschlager',
  'Grain Alcohol',
  'Grand Marnier',
  'Guinness stout',
  'Guinness',
  'Irish cream',
  'Irish Whiskey',
  'Jack Daniels',
  'Jgermeister',
  'Johnnie Walker',
  'J„germeister',
  'Kahlua',
  'Kirschwasser',
  'Light Rum',
  'Malibu Rum',
  'Midori melon liqueur',
  'Peach Schnapps',
  'Pernod',
  'Peychaud bitters',
  'Pisco',
  'Port',
  'Red Wine',
  'Ricard',
  'Rum',
  'Rumple Minze',
  'Sake',
  'Sambuca',
  'Scotch',
  'Sherry',
  'Sloe Gin',
  'Southern Comfort',
  'Spiced Rum',
  'Tequila',
  'Tennessee whiskey',
  'Tia Maria',
  'Vermouth',
  'Vodka',
  'Whiskey',
  'White Creme de Menthe',
  'White Rum',
  'White Wine',
  'Wild Turkey',
  'Wine',
  'Yukon Jack',
];
